### PR TITLE
Meteor.settings.public is not accessible on the client

### PR DESCRIPTION
**Pull request by darkbasic**
Meteor.settings.public is not accessible on the client when using Ionic 2 with meteor-client-bundle, better use options if available.

### CODE REVIEW

**Comment by yuyinitos** [comment]
Please update atmosphere. Changes are not pulled when using `meteor add btafel:accounts-facebook-cordova`

**Comment by darkbasic** [comment]
Updating atmosphere would be nice indeed, I will soon release a new version of the Angular Meteor tutorial and I will have to publish my own package if atmosphere doesn't get updated.

**Comment by btafel** [comment]
I'll update this later tonight

________________________________

**Comment by btafel** [comment]
done!

> Published btafel:accounts-facebook-cordova@0.0.7.

**Pull request merged**
